// Date parsing for order fields written to Postgres, specific to this app's
// own wire formats - do NOT reuse grfmxstatusupdate's parseDate()/
// parseDateOfBirth(), those are shaped for its legacy Mongo strings, which
// use different separators/timezone assumptions than this app's own fields.

// gorush-client always sends dateOfBirth as zero-padded, dot-separated
// DD.MM.YYYY (confirmed: components/order/IdentityFields.js, both the native
// picker and web <input type="date"> paths - e.g. "28.06.1948"). dateOfBirth
// maps to a @db.Date column (no time-of-day) - construct the UTC calendar
// date directly from the Y/M/D components, with no timezone conversion at
// all. (grfmxstatusupdate hit a real bug doing this via a timezone-aware
// parser for its own dateOfBirth field - a midnight-local instant shifts to
// the previous day once only the date part survives into a @db.Date column.
// Building the UTC date directly here avoids that class of bug entirely.)
function parseGorushDateOfBirth(value) {
    if (value === null || value === undefined || value === '') return null;
    const m = /^(\d{2})\.(\d{2})\.(\d{4})$/.exec(String(value).trim());
    if (!m) return null;
    const day = Number(m[1]);
    const month = Number(m[2]);
    const year = Number(m[3]);
    if (month < 1 || month > 12 || day < 1 || day > 31) return null;
    const d = new Date(Date.UTC(year, month - 1, day));
    return Number.isNaN(d.getTime()) ? null : d;
}

// dateTimeSubmission is always now.toISOString() - an explicit-UTC ("Z")
// string generated by this app itself, so there's no naive-local-string
// ambiguity here (unlike grfmxstatusupdate's legacy Mongo data) - a plain
// Date parse is correct and sufficient.
function parseGorushIso(value) {
    if (value === null || value === undefined || value === '') return null;
    const d = new Date(value);
    return Number.isNaN(d.getTime()) ? null : d;
}

module.exports = { parseGorushDateOfBirth, parseGorushIso };
